/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\Calem_anims.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Calem_anims.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Calem002">
            <skinnedMesh
              name="Calem003"
              geometry={nodes.Calem003.geometry}
              material={materials["Material #247.003"]}
              skeleton={nodes.Calem003.skeleton}
            />
            <skinnedMesh
              name="Calem003_1"
              geometry={nodes.Calem003_1.geometry}
              material={materials["Material #248.003"]}
              skeleton={nodes.Calem003_1.skeleton}
            />
            <skinnedMesh
              name="Calem003_2"
              geometry={nodes.Calem003_2.geometry}
              material={materials["Material #249.003"]}
              skeleton={nodes.Calem003_2.skeleton}
            />
            <skinnedMesh
              name="Calem003_3"
              geometry={nodes.Calem003_3.geometry}
              material={materials["Material #250.003"]}
              skeleton={nodes.Calem003_3.skeleton}
            />
            <skinnedMesh
              name="Calem003_4"
              geometry={nodes.Calem003_4.geometry}
              material={materials["Material #251.003"]}
              skeleton={nodes.Calem003_4.skeleton}
            />
            <skinnedMesh
              name="Calem003_5"
              geometry={nodes.Calem003_5.geometry}
              material={materials["Material #252.003"]}
              skeleton={nodes.Calem003_5.skeleton}
            />
            <skinnedMesh
              name="Calem003_6"
              geometry={nodes.Calem003_6.geometry}
              material={materials["Material #253.003"]}
              skeleton={nodes.Calem003_6.skeleton}
            />
            <skinnedMesh
              name="Calem003_7"
              geometry={nodes.Calem003_7.geometry}
              material={materials["Material #254.003"]}
              skeleton={nodes.Calem003_7.skeleton}
            />
            <skinnedMesh
              name="Calem003_8"
              geometry={nodes.Calem003_8.geometry}
              material={materials["Material #255.003"]}
              skeleton={nodes.Calem003_8.skeleton}
            />
            <skinnedMesh
              name="Calem003_9"
              geometry={nodes.Calem003_9.geometry}
              material={materials["Material #256.003"]}
              skeleton={nodes.Calem003_9.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Calem_anims.glb");
