/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\foods.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/foods.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="table" geometry={nodes.table.geometry} material={materials['795548']} />
      <mesh name="cupcake008" geometry={nodes.cupcake008.geometry} material={materials['_defaultMat.003']} />
      <mesh name="cupcake008_1" geometry={nodes.cupcake008_1.geometry} material={materials['purpleLight.003']} />
      <mesh name="cupcake008_2" geometry={nodes.cupcake008_2.geometry} material={materials['brownDark.003']} />
      <mesh name="cupcake008_3" geometry={nodes.cupcake008_3.geometry} material={materials.brown} />
      <mesh name="cupcake008_4" geometry={nodes.cupcake008_4.geometry} material={materials['red.003']} />
      <mesh name="cupcake008_5" geometry={nodes.cupcake008_5.geometry} material={materials['green.001']} />
      <mesh name="cupcake008_6" geometry={nodes.cupcake008_6.geometry} material={materials['brownDarkest.001']} />
      <mesh name="cupcake008_7" geometry={nodes.cupcake008_7.geometry} material={materials['_defaultMat.001']} />
      <mesh name="cupcake008_8" geometry={nodes.cupcake008_8.geometry} material={materials['red.001']} />
      <mesh name="cupcake008_9" geometry={nodes.cupcake008_9.geometry} material={materials.brownLight} />
      <mesh name="cupcake008_10" geometry={nodes.cupcake008_10.geometry} material={materials['purpleLight.001']} />
      <mesh name="cupcake008_11" geometry={nodes.cupcake008_11.geometry} material={materials['brownDark.001']} />
      <mesh name="cupcake008_12" geometry={nodes.cupcake008_12.geometry} material={materials.材质} />
      <mesh name="cupcake008_13" geometry={nodes.cupcake008_13.geometry} material={materials.brownDarkest} />
      <mesh name="cupcake008_14" geometry={nodes.cupcake008_14.geometry} material={materials.brownDark} />
      <mesh name="cupcake008_15" geometry={nodes.cupcake008_15.geometry} material={materials.purpleLight} />
      <mesh name="cupcake008_16" geometry={nodes.cupcake008_16.geometry} material={materials._defaultMat} />
      <mesh name="cupcake008_17" geometry={nodes.cupcake008_17.geometry} material={materials.red} />
      <mesh name="cupcake008_18" geometry={nodes.cupcake008_18.geometry} material={materials.purple} />
      <mesh name="cupcake008_19" geometry={nodes.cupcake008_19.geometry} material={materials.yellow} />
      <mesh name="cupcake008_20" geometry={nodes.cupcake008_20.geometry} material={materials['_defaultMat.002']} />
      <mesh name="cupcake008_21" geometry={nodes.cupcake008_21.geometry} material={materials['purpleLight.002']} />
      <mesh name="cupcake008_22" geometry={nodes.cupcake008_22.geometry} material={materials['brownDark.002']} />
      <mesh name="cupcake008_23" geometry={nodes.cupcake008_23.geometry} material={materials['mat20.001']} />
      <mesh name="cupcake008_24" geometry={nodes.cupcake008_24.geometry} material={materials['mat18.002']} />
      <mesh name="cupcake008_25" geometry={nodes.cupcake008_25.geometry} material={materials['mat18.001']} />
      <mesh name="cupcake008_26" geometry={nodes.cupcake008_26.geometry} material={materials.mat20} />
      <mesh name="cupcake008_27" geometry={nodes.cupcake008_27.geometry} material={materials['mat21.001']} />
      <mesh name="cupcake008_28" geometry={nodes.cupcake008_28.geometry} material={materials.LightYellow} />
      <mesh name="cupcake008_29" geometry={nodes.cupcake008_29.geometry} material={materials.PalePink} />
      <mesh name="cupcake008_30" geometry={nodes.cupcake008_30.geometry} material={materials.Blue} />
      <mesh name="cupcake008_31" geometry={nodes.cupcake008_31.geometry} material={materials.Green} />
      <mesh name="cupcake008_32" geometry={nodes.cupcake008_32.geometry} material={materials['Red.001']} />
      <mesh name="cupcake008_33" geometry={nodes.cupcake008_33.geometry} material={materials['Sprinkle2.002']} />
      <mesh name="cupcake008_34" geometry={nodes.cupcake008_34.geometry} material={materials['Frosting.002']} />
      <mesh name="cupcake008_35" geometry={nodes.cupcake008_35.geometry} material={materials['default.002']} />
      <mesh name="cupcake008_36" geometry={nodes.cupcake008_36.geometry} material={materials.lambert5SG} />
      <mesh name="cupcake008_37" geometry={nodes.cupcake008_37.geometry} material={materials.initialShadingGroup} />
      <mesh name="cupcake008_38" geometry={nodes.cupcake008_38.geometry} material={materials['lambert3SG.001']} />
      <mesh name="cupcake008_39" geometry={nodes.cupcake008_39.geometry} material={materials.lambert2SG} />
      <mesh name="cupcake008_40" geometry={nodes.cupcake008_40.geometry} material={materials['lambert4SG.001']} />
      <mesh name="cupcake008_41" geometry={nodes.cupcake008_41.geometry} material={materials.PorcelainPlate1} />
      <mesh name="cupcake008_42" geometry={nodes.cupcake008_42.geometry} material={materials['PorcelainPlate1.001']} />
      <mesh name="cupcake008_43" geometry={nodes.cupcake008_43.geometry} material={materials.lambert4SG} />
      <mesh name="cupcake008_44" geometry={nodes.cupcake008_44.geometry} material={materials.lambert3SG} />
      <mesh name="cupcake008_45" geometry={nodes.cupcake008_45.geometry} material={materials['mat20.003']} />
      <mesh name="cupcake008_46" geometry={nodes.cupcake008_46.geometry} material={materials.mat23} />
      <mesh name="cupcake008_47" geometry={nodes.cupcake008_47.geometry} material={materials['mat8.002']} />
      <mesh name="cupcake008_48" geometry={nodes.cupcake008_48.geometry} material={materials.mat10} />
      <mesh name="cupcake008_49" geometry={nodes.cupcake008_49.geometry} material={materials['mat19.001']} />
      <mesh name="cupcake008_50" geometry={nodes.cupcake008_50.geometry} material={materials.DarkBrown} />
      <mesh name="cupcake008_51" geometry={nodes.cupcake008_51.geometry} material={materials.mat24} />
      <mesh name="cupcake008_52" geometry={nodes.cupcake008_52.geometry} material={materials.mat21} />
      <mesh name="cupcake008_53" geometry={nodes.cupcake008_53.geometry} material={materials.mat14} />
      <mesh name="cupcake008_54" geometry={nodes.cupcake008_54.geometry} material={materials.mat13} />
      <mesh name="cupcake008_55" geometry={nodes.cupcake008_55.geometry} material={materials.mat18} />
      <mesh name="cupcake008_56" geometry={nodes.cupcake008_56.geometry} material={materials['_defaultMat.004']} />
      <mesh name="cupcake008_57" geometry={nodes.cupcake008_57.geometry} material={materials['brownLight.001']} />
      <mesh name="cupcake008_58" geometry={nodes.cupcake008_58.geometry} material={materials['brown.001']} />
      <mesh name="cupcake008_59" geometry={nodes.cupcake008_59.geometry} material={materials['green.002']} />
      <mesh name="cupcake008_60" geometry={nodes.cupcake008_60.geometry} material={materials.orange} />
      <mesh name="cupcake008_61" geometry={nodes.cupcake008_61.geometry} material={materials['mat21.002']} />
      <mesh name="cupcake008_62" geometry={nodes.cupcake008_62.geometry} material={materials.mat9} />
      <mesh name="cupcake008_63" geometry={nodes.cupcake008_63.geometry} material={materials.mat8} />
      <mesh name="cupcake008_64" geometry={nodes.cupcake008_64.geometry} material={materials['mat18.003']} />
      <mesh name="cupcake008_65" geometry={nodes.cupcake008_65.geometry} material={materials.White} />
      <mesh name="cupcake008_66" geometry={nodes.cupcake008_66.geometry} material={materials.Red} />
      <mesh name="cupcake008_67" geometry={nodes.cupcake008_67.geometry} material={materials.mat16} />
      <mesh name="cupcake008_68" geometry={nodes.cupcake008_68.geometry} material={materials['mat8.001']} />
      <mesh name="cupcake008_69" geometry={nodes.cupcake008_69.geometry} material={materials['mat20.002']} />
      <mesh name="cupcake008_70" geometry={nodes.cupcake008_70.geometry} material={materials.mat19} />
      <mesh name="cupcake008_71" geometry={nodes.cupcake008_71.geometry} material={materials['mat18.004']} />
      <mesh name="cupcake008_72" geometry={nodes.cupcake008_72.geometry} material={materials.mat15} />
      <mesh name="cupcake008_73" geometry={nodes.cupcake008_73.geometry} material={materials.Atlas} />
    </group>
  )
}

useGLTF.preload('/foods.glb')
