/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\forests1.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/forests1.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="house1"
          geometry={nodes.house1.geometry}
          material={nodes.house1.material}
        />
        <mesh
          name="house2"
          geometry={nodes.house2.geometry}
          material={nodes.house2.material}
        />
        <mesh
          name="平面003"
          geometry={nodes.平面003.geometry}
          material={nodes.平面003.material}
        />
        <mesh
          name="house3"
          geometry={nodes.house3.geometry}
          material={nodes.house3.material}
        />
        <mesh
          name="stones"
          geometry={nodes.stones.geometry}
          material={nodes.stones.material}
        />
        <mesh
          name="river"
          geometry={nodes.river.geometry}
          material={nodes.river.material}
        />
        <mesh
          name="house4"
          geometry={nodes.house4.geometry}
          material={nodes.house4.material}
        />
        <mesh
          name="plants"
          geometry={nodes.plants.geometry}
          material={nodes.plants.material}
        />
        <mesh
          name="bowl"
          geometry={nodes.bowl.geometry}
          material={nodes.bowl.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/forests1.glb");
