/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\character.glb -k 
*/

import React, { useRef, useEffect, useMemo } from "react";
import { useGLTF, useTexture, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import {
  Physics,
  RigidBody,
  CuboidCollider,
  BallCollider,
  CylinderCollider,
  InstancedRigidBodies,
  useRapier,
} from "@react-three/rapier";
export function Character(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/character.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions);

  // 设置自发光材质
  const emissionMaterial = (ref) => {
    ref.current.traverse((child) => {
      if (child.isMesh && child.material) {
        if (Array.isArray(child.material)) {
          child.material.forEach(setEmissive);
        } else {
          const m = child.material;
          m.emissive = m.color;
          m.emissiveMap = m.map;
          m.emissiveIntensity = 0.5;
        }
      }
    });
  };
  useEffect(() => {
    // 遍历模型中的每个材质并设置自发光
    emissionMaterial(group);
  }, []);
  useFrame(() => {
    // console.log(group.current.position);
  });
  return (
    <>
      {/* <CuboidCollider args={[0.3, 1, 0.5]} position={[0, 1.5, 0]} /> */}
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature003" rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.mixamorigHips} />
            <group name="Serena003">
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004"
                geometry={nodes.Serena004.geometry}
                material={materials["Material #291.004"]}
                skeleton={nodes.Serena004.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_1"
                geometry={nodes.Serena004_1.geometry}
                material={materials["Material #292.004"]}
                skeleton={nodes.Serena004_1.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_2"
                geometry={nodes.Serena004_2.geometry}
                material={materials["Material #293.004"]}
                skeleton={nodes.Serena004_2.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_3"
                geometry={nodes.Serena004_3.geometry}
                material={materials["Material #294.004"]}
                skeleton={nodes.Serena004_3.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_4"
                geometry={nodes.Serena004_4.geometry}
                material={materials["Material #295.004"]}
                skeleton={nodes.Serena004_4.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_5"
                geometry={nodes.Serena004_5.geometry}
                material={materials["Material #296.004"]}
                skeleton={nodes.Serena004_5.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_6"
                geometry={nodes.Serena004_6.geometry}
                material={materials["Material #297.004"]}
                skeleton={nodes.Serena004_6.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_7"
                geometry={nodes.Serena004_7.geometry}
                material={materials["Material #298.004"]}
                skeleton={nodes.Serena004_7.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_8"
                geometry={nodes.Serena004_8.geometry}
                material={materials["Material #299.004"]}
                skeleton={nodes.Serena004_8.skeleton}
              />
              <skinnedMesh
                receiveShadow
                castShadow
                name="Serena004_9"
                geometry={nodes.Serena004_9.geometry}
                material={materials["Material #300.004"]}
                skeleton={nodes.Serena004_9.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/models/character.glb");
