/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\chocolate.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CapsuleCollider } from "@react-three/rapier";
export function Chochlate(props) {
  const { nodes, materials } = useGLTF("/models/chocolate.glb");
  return (
    <group {...props} dispose={null} scale={13} position={[-51, 3, 56.5]}>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate1_1"
            geometry={nodes.chocolate1_1.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate1_2"
            geometry={nodes.chocolate1_2.geometry}
            material={materials.lambert4SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <mesh
          name="chocolate2_1"
          geometry={nodes.chocolate2_1.geometry}
          material={materials.lambert5SG}
        />
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate2_2"
            geometry={nodes.chocolate2_2.geometry}
            material={materials.lambert4SG}
          />
          <mesh
            name="chocolate3_1"
            geometry={nodes.chocolate3_1.geometry}
            material={materials.initialShadingGroup}
          />
          <mesh
            name="chocolate3_2"
            geometry={nodes.chocolate3_2.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate3_3"
            geometry={nodes.chocolate3_3.geometry}
            material={materials.lambert2SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <mesh
          name="chocolate4_1"
          geometry={nodes.chocolate4_1.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          name="chocolate4_2"
          geometry={nodes.chocolate4_2.geometry}
          material={materials.lambert4SG}
        />
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate5_1"
            geometry={nodes.chocolate5_1.geometry}
            material={materials.lambert5SG}
          />
          <mesh
            name="chocolate5_2"
            geometry={nodes.chocolate5_2.geometry}
            material={materials.lambert3SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate6_1"
            geometry={nodes.chocolate6_1.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate6_2"
            geometry={nodes.chocolate6_2.geometry}
            material={materials.lambert4SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate1_1"
            geometry={nodes.chocolate1_1.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate1_2"
            geometry={nodes.chocolate1_2.geometry}
            material={materials.lambert4SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <mesh
          name="chocolate2_1"
          geometry={nodes.chocolate2_1.geometry}
          material={materials.lambert5SG}
        />
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate2_2"
            geometry={nodes.chocolate2_2.geometry}
            material={materials.lambert4SG}
          />
          <mesh
            name="chocolate3_1"
            geometry={nodes.chocolate3_1.geometry}
            material={materials.initialShadingGroup}
          />
          <mesh
            name="chocolate3_2"
            geometry={nodes.chocolate3_2.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate3_3"
            geometry={nodes.chocolate3_3.geometry}
            material={materials.lambert2SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <mesh
          name="chocolate4_1"
          geometry={nodes.chocolate4_1.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          name="chocolate4_2"
          geometry={nodes.chocolate4_2.geometry}
          material={materials.lambert4SG}
        />
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate5_1"
            geometry={nodes.chocolate5_1.geometry}
            material={materials.lambert5SG}
          />
          <mesh
            name="chocolate5_2"
            geometry={nodes.chocolate5_2.geometry}
            material={materials.lambert3SG}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="ball" name="choclate">
        <group>
          <mesh
            name="chocolate6_1"
            geometry={nodes.chocolate6_1.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            name="chocolate6_2"
            geometry={nodes.chocolate6_2.geometry}
            material={materials.lambert4SG}
          />
        </group>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/chocolate.glb");
