/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\foods.glb -k 
*/

import React, { useRef, useState } from "react";
import { useGLTF, Html } from "@react-three/drei";
import {
  CuboidCollider,
  CylinderCollider,
  RigidBody,
  InstancedRigidBodies,
  CapsuleCollider,
} from "@react-three/rapier";
import { Button, Popover } from "antd";

export function Foods(props) {
  const group = useRef();
  const { nodes, scene, materials } = useGLTF("/models/foods.glb");
  const [isTouch, setisTouch] = useState(false);
  const audioRef = useRef(new Audio("/sounds/happyBirthday.mp3"));
  return (
    <group
      {...props}
      ref={group}
      dispose={null}
      position={[-38, 1.3, -186]}
      scale={6}
    >
      <RigidBody
        name="table"
        type="fixed"
        colliders="trimesh"
        onCollisionEnter={({ manifold, target, other }) => {
          console.log(
            "Collision at world position ",
            manifold.solverContactPoint(0)
          );

          if (
            other.rigidBodyObject &&
            other.rigidBodyObject.name == "character"
          ) {
            console.log(
              target.rigidBodyObject.name,
              " collided with ",
              other.rigidBodyObject.name
            );
            setisTouch(true);
            audioRef.current.play();
          }
        }}
        onCollisionExit={() => {
          console.log("离开桌子");
          setisTouch(false);
          audioRef.current.pause();
        }}
      >
        <mesh
          name="table"
          geometry={nodes.table.geometry}
          material={materials["795548"]}
        />
        <Html
          position={[0.5, 0.15, 0]}
          // position={[-38, 2, -186]}
          wrapperClass="label"
          center
          distanceFactor={6}
          occlude={[group]}
        >
          <Popover
            trigger="hover"
            open={isTouch}
            content={
              <div>
                <p>MYK,终于等到你啦！</p>
                <p>祝你生日快乐o(*￣▽￣*)ブ</p>
                <p>这是骑士大人为你准备的你最喜欢的事食物</p>
              </div>
            }
            title="MESSAGE :"
          >
            <Button type={`primary ${isTouch && "touch"}`}>Hi! MYk</Button>
          </Popover>
        </Html>
      </RigidBody>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/models/foods.glb");
