/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/land.glb -o src/components/gltf/World.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, OrbitControls } from "@react-three/drei";
import {
  Physics,
  RigidBody,
  CuboidCollider,
  BallCollider,
  CylinderCollider,
  InstancedRigidBodies,
} from "@react-three/rapier";
export function World(props) {
  const group = useRef();
  const { nodes, scene, materials, animations } = useGLTF("/models/land.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <Physics debug>
      <ambientLight intensity={0.5} />
      <directionalLight intensity={1} position={[1, 3, 1]} />
      <OrbitControls />
      <group ref={group} {...props} dispose={null} scale={0.1}>
        <primitive object={scene} />
      </group>
    </Physics>
  );
}

useGLTF.preload("/models/land.glb");
